services:
    postgres:
      image: postgres:15
      container_name: postgres
      restart: always
      environment:
        - POSTGRES_DB=swift_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./db_scripts:/docker-entrypoint-initdb.d
    app:
      build: .
      container_name: swift_app
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swift_db
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: admin
        SPRING_JPA_HIBERNATE_DDL_AUTO: none
        SPRING_PROFILES_ACTIVE: docker
volumes:
  postgres_data: