spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swift_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

swift:
  loader:
    file-path: classpath:Interns_2025_SWIFT_CODES.xlsx